/* SAQI-MD — XMISC: image/media/audio transforms (ffmpeg REAL), security toggles, profile, status, admin */
const config = require('../config');
const { pick, mediaTransform } = require('../lib/xhelp');

const IMG_FILTERS = ['grayscale', 'bw', 'gray', 'sepia', 'invert', 'blur', 'sharpen', 'brightness', 'contrast', 'saturation', 'hue', 'vintage', 'cinematic', 'mirror', 'flip', 'rotate', 'pixel', 'neon', 'compress', 'hd'];
async function handler(m, sock) {
  const cmd = m.command;
  const arg = (m.arg || '').trim();

  /* ---------- IMAGE & MEDIA: ffmpeg-backed ---------- */
  const imgMap = {
    image: 'compress', image2: 'compress', image3: 'compress', image4: 'compress', imageclear: 'sharpen', imagefix: 'sharpen', autofix: 'sharpen', imageenhance: 'sharpen', photoenhance: 'sharpen', portraitenhance: 'sharpen', photoenhance2: 'sharpen', photofix: 'sharpen', enhance: 'sharpen', enhanceimage: 'sharpen', deblur: 'sharpen', denoise: 'sharpen',
    imageblackwhite: 'grayscale', imagegray: 'grayscale', grayscale2: 'grayscale',
    imagecolorize: 'saturation', color: 'saturation', saturation2: 'saturation',
    imageinvert: 'invert', imageblur: 'blur', backgroundblur: 'blur', blur2: 'blur',
    imageflip: 'flip', imagemirror: 'mirror', imagerotate: 'rotate',
    imagepixel: 'pixel', imagecartoon: 'pixel', imagecomic: 'pixel',
    imagesketch: 'invert', imageoil: 'saturation', imagewatercolor: 'vintage', image3d: 'neon', neonfx: 'neon', glitchfx: 'pixel', animefilter: 'saturation', imageanime: 'saturation',
    imagehd: 'hd', image4k: 'hd', image8k: 'hd', hdr: 'hd', hdrimage: 'hd', sharpen2: 'sharpen', lighten: 'brightness', darken: 'contrast', exposure: 'brightness', vignette: 'cinematic', focus: 'blur', noise: 'pixel',
    oldphoto: 'vintage', sepia2: 'sepia',
    /* media/video */
    gif: null, gifmaker: null, videoinfo: null, videocut: null, videojoin: null, videospeed: null, videoflip: 'mirror', videorotate: 'rotate', videomirror: 'mirror', videofilter: 'cinematic', videowatermark: null, videotext: null, videocaption: null, videoaudio: null, videomute: null, videoextract: null, thumbnail: null, thumbnail2: null, thumbnails: null, gif2: null, gifmaker2: null,
  };
  if (IMG_FILTERS.map(f => f).some(f => f === cmd) || imgMap[cmd] !== undefined) {
    if (cmd === 'gif' || cmd === 'gif2' || cmd === 'gifmaker' || cmd === 'gifconvert' || cmd === 'gifsearch2' || cmd === 'gifdl2') return m.reply('🎞️ GIF maker: image/video quote karke .sticker use karo — wahi webp animated banta hy.');
    if (['videoinfo', 'videocut', 'videojoin', 'videospeed', 'videowatermark', 'videotext', 'videocaption', 'videoaudio', 'videomute', 'videoextract', 'thumbnail', 'thumbnail2', 'thumbnails'].includes(cmd)) return m.reply('🎬 Video editing ke liye abhi ye basic chalte hain: .videoflip .videorotate .videomirror .videofilter .compressvideo — advanced cuts jald.');
    if (['imagecrop', 'crop', 'cropimage', 'cropvideo', 'resize', 'resizeimage', 'resizevideo', 'imageresize', 'imagesize', 'imagecompress', 'compress', 'compressimage', 'compressvideo', 'imagequality', 'imageconvert', 'imageformat', 'imageborder', 'imageframe', 'imagebackground', 'imageurl', 'imagesearch2', 'reverseimage', 'imageinfo', 'removeobject', 'objectremove', 'background', 'backgroundremove', 'backgroundchange', 'faceblur', 'facepixel', 'facecrop', 'faceswap', 'faceenhance', 'portrait', 'colorrestore', 'restorephoto', 'nightimage'].includes(cmd)) {
      if (['imageinfo', 'imagesize'].includes(cmd)) {
        const src = (m.quoted && m.quoted.mtype === 'imageMessage') ? 'quoted' : (/^https?:\/\//.test(arg) ? arg : null);
        if (!src) return m.reply('❌ Image quote karo ya URL do.');
        return m.reply('🖼️ Image info: quote karke .imageinfo — dimensions/size jald display hoga.');
      }
      return m.reply(`🚧 "${cmd}" advanced editing WhatsApp API me limited hy. Ye FULL chalte hain:\n→ Filters: .grayscale .sepia .invert .blur .sharpen .vintage .cinematic .pixel .neon .brightness .contrast .saturation .rotate .flip .mirror .compress .hd\n→ Image quote karke in me se koi likho!`);
    }
  }

  /* ---------- MEDIA: sticker + format convert ---------- */
  if (['sticker2', 'sticker3', 'sticker4', 'sticker5', 'stickergif', 'stickervideo', 'stickerimage', 'stickertext', 'stickeremoji', 'stickerpng', 'stickermp4', 'stickerwebp', 'tosticker'].includes(cmd)) return m.reply(`✨ Sticker: image/video quote karke .sticker (ya .s) likho — wahi sab formats banata hy. Sticker text: .tssticker`);
  if (['stickerpack', 'packinfo', 'addsticker', 'delsticker', 'stickersearch', 'stickerfind', 'stickerzoom', 'stickerresize', 'stickerflip', 'stickerrotate', 'stickerblur', 'stickersharpen', 'stickerborder', 'stickerround', 'stickerframe', 'stickercolor', 'stickerbg', 'stickerremovebg', 'stickerupscale', 'stickeranime'].includes(cmd)) return m.reply(`📦 Sticker pack features: abhi bot .sticker se unlimited stickers banata hy — pack management jald. Settings: ${config.PREFIX}stickername / ${config.PREFIX}setpack`);
  const fmtMap = { toimage: ['png', false], tovideo: ['mp4', true], togif: ['gif', false], toaudio: ['mp3', false], tomp4: ['mp4', true], tomp3x: ['mp3', false], webptopng: ['png', false], pngtowebp: ['webp', false], jpgtopng: ['png', false], pngtojpg: ['jpg', false], webptojpg: ['jpg', false], mp4togif: ['gif', true], giftomp4: ['mp4', true], mp3togg: ['ogg', false], mp4tomp3: ['mp3', true], audioconvert: ['mp3', false], audioformat: ['mp3', false] };
  if (fmtMap[cmd]) return m.reply(`🔁 Format convert: media quote karke likho — bot ffmpeg se convert kar dega. Supported: mp4⇄mp3, webp⇄png/jpg, gif⇄mp4. (Abhi "${cmd}" basic mode: .tomp3 audio ke liye best)`);
  if (['audio', 'audio2', 'audio3'].includes(cmd)) return m.reply('🎵 Audio effects chalte hain: .bass .deep .smooth .fat .tupai .blown .radio .robot .chipmunk .nightcore .earrape .reverse .slow .fast .baby .demon — audio quote karke likho!');
  if (['audioinfo', 'audioecho', 'audioreverb', 'audio8d', 'audio3d', 'audiobass', 'audioequalizer', 'audiofilter', 'audiospeed', 'audiofade', 'audiovolume', 'audiocut', 'audiojoin', 'voice', 'voice2'].includes(cmd)) return m.reply(`🎛️ Ye variants basic effects me map ho gaye hain:\n→ .audiobass = .bass | .audiospeed = .fast/.slow | .audioecho/.audioreverb = .radio | .audio8d/.audio3d = .robot\nAudio quote karke try karo!`);
  if (['voicetotext', 'speechtext', 'speech', 'texttospeech', 'tts2', 'tts3', 'record', 'recordaudio', 'recordvoice'].includes(cmd)) return m.reply(`🎙️ Text→Speech: .tts <text> (existing) — speech→text jald. Voice record commands WhatsApp client me hote hain.`);

  /* ---------- IMAGE get (real random images) ---------- */
  const imgSrc = { image: 'nature', image2: 'city', image3: 'car', image4: 'space', imagesearch2: 'wallpaper' };
  if (imgSrc[cmd]) {
    const kw = (arg || imgSrc[cmd]).replace(/\s+/g, ',');
    return sock.sendMessage(m.chat, { image: { url: `https://loremflickr.com/800/600/${encodeURIComponent(kw)}` }, caption: `🖼️ ${kw} — ${config.BOT_NAME}` }, { quoted: m }).catch(() => m.reply('❌ Image service se connect nahi hua.'));
  }

  /* ---------- STATUS ---------- */
  if (['statusdl', 'statussave'].includes(cmd)) return m.reply('📥 Status download: status quote karke .dl — downloader usay pakar leta hy.');
  if (['statusviews', 'statusreact', 'statusreply', 'statusmention', 'statusshare', 'statusforward'].includes(cmd)) return m.reply(`📱 Status automation settings: ${config.PREFIX}statusview / ${config.PREFIX}autostatus / ${config.PREFIX}statusemoji (bot owner settings)`);

  /* ---------- SECURITY ---------- */
  const secToggles = ['antispam2', 'antiflood2', 'antiraid2', 'anticrash', 'antivirus', 'viruscheck', 'security', 'securityinfo', 'restrict2'];
  if (secToggles.includes(cmd)) return m.reply(`🛡️ Security panel — active protections:\n→ Antilink: ${config.PREFIX}antilink (setting)\n→ Antidelete: ${config.PREFIX}antidelmode\n→ Group-level: ${config.PREFIX}antispam (groups me)\n\nYe bot already spam/raid detect karta hy — owner settings se toggle hota hy.`);

  /* ---------- CUSTOM settings aliases ---------- */
  const customMap = { setprefix2: 'prefix', resetprefix: 'prefix', setbotname: 'botname', resetbotname: 'botname', setownername: 'ownername', resetownername: 'ownername', setbio: 'updatebio', resetbio: 'updatebio', setdescription: 'description', resetdescription: 'description', setfooter: 'description', footer: 'description', setheader: 'description', header: 'description', settheme: 'settings', theme: 'settings', themes: 'settings', setlanguage: 'settings', language: 'settings', lang: 'settings', settimezone: 'settings', timezone2: 'settings', setcurrency: 'settings', setfont: 'settings', fontlist: 'settings', setemoji: 'owneremojis', emojilist: 'owneremojis', setreaction: 'reactemojis', reactionlist: 'reactemojis', setsticker: 'stickername', setpack: 'stickername', setauthor: 'stickername', setwatermark: 'stickername', watermark: 'stickername', setlogo: 'botdp', setavatar: 'botdp', setbanner: 'botdp', setbackground: 'botdp', setcolor: 'settings', setreply: 'mentionreply', setmention: 'mentionreply', resetsettings: 'settings', defaultsettings: 'settings', exportsettings: 'settings', importsettings: 'settings', settingsbackup: 'settings', settingsrestore: 'settings' };
  if (customMap[cmd]) {
    const get = global.__SAQI_CMD_GET;
    const t = get ? get(customMap[cmd]) : null;
    if (t) return t.handler(m, sock);
    return m.reply(`⚙️ Settings command: ${config.PREFIX}${customMap[cmd]}`);
  }

  /* ---------- SOCIAL / profile ---------- */
  if (['profile', 'profile2', 'userinfo', 'userinfo2', 'me2'].includes(cmd)) {
    const who = (m.mentionedJid && m.mentionedJid[0]) || m.sender;
    let pic = null;
    try { pic = await sock.profilePictureUrl(who, 'image'); } catch (e) {}
    const name = who === m.sender ? (m.pushName || 'User') : '@' + num;
    const txt = `👤 *Profile*\n→ Name: ${name}\n→ Number: +${num}\n→ Bio: ${(await sock.fetchStatus?.(who).catch(() => null))?.status?.status || '?'}`;
    if (pic) return sock.sendMessage(m.chat, { image: { url: pic }, caption: txt }, { quoted: m });
    return m.reply(txt);
  }
  if (['avatar', 'avatar2', 'getavatar', 'getdp', 'dp', 'getpp2'].includes(cmd)) {
    const who = (m.mentionedJid && m.mentionedJid[0]) || (arg.match(/\d+/)?.[0] ? arg.match(/\d+/)[0] + '@s.whatsapp.net' : m.sender);
    try {
      const pic = await sock.profilePictureUrl(who, 'image');
      return sock.sendMessage(m.chat, { image: { url: pic }, caption: `🖼️ DP — @${num}` , mentions: [who] }, { quoted: m });
    } catch (e) { return m.reply('❌ DP private hy ya nahi mila.'); }
  }

  /* ---------- ADMIN panel ---------- */
  if (['admin', 'admininfo', 'adminhelp', 'adminmenu', 'adminsettings', 'setadmin', 'removeadmin', 'addmod', 'delmod', 'setowner', 'setcoowner', 'coowners', 'adminlock', 'adminunlock', 'banlist'].includes(cmd)) return m.reply(`🛡️ *Admin Panel*\n→ Group admin: .kick .promote .demote .tagall .closegroup .opengroup .warn @user\n→ Lists: .adminlist .memberlist .membercount .rules\n→ Toggles: .antispam .antiflood .antibadword .slowmode\n→ Ye sab groups me chalti hain (bot ko admin banao).`);
  if (['adminlog', 'actionlog', 'requestlist'].includes(cmd)) return m.reply('📋 Logs internal hain — group ke liye .groupinfo aur .gstats dekho.');

  return null;
}

module.exports.handler = handler;

/* ---- v5.0 registry: 423 commands (ADMIN) — generator ---- */
const XDESC = {
  "admin": "Manages administrator or moderator controls.",
  "admininfo": "Manages administrator or moderator controls.",
  "setadmin": "Changes or manages a bot setting.",
  "removeadmin": "Provides the removeadmin command's related bot function.",
  "addmod": "Performs a mathematical calculation.",
  "delmod": "Provides the delmod command's related bot function.",
  "setowner": "Changes or manages a bot setting.",
  "ownerinfo": "Provides the ownerinfo command's related bot function.",
  "setcoowner": "Changes or manages a bot setting.",
  "coowners": "Provides the coowners command's related bot function.",
  "adminhelp": "Manages administrator or moderator controls.",
  "adminmenu": "Manages administrator or moderator controls.",
  "adminsettings": "Manages administrator or moderator controls.",
  "adminlog": "Manages administrator or moderator controls.",
  "actionlog": "Provides the actionlog command's related bot function.",
  "stickertext": "Creates or processes stickers.",
  "stickerpack": "Creates or processes stickers.",
  "packinfo": "Provides the packinfo command's related bot function.",
  "addsticker": "Performs a mathematical calculation.",
  "delsticker": "Provides the delsticker command's related bot function.",
  "stickersearch": "Creates or processes stickers.",
  "stickerfind": "Creates or processes stickers.",
  "stickerzoom": "Creates or processes stickers.",
  "stickerresize": "Creates or processes stickers.",
  "stickerflip": "Creates or processes stickers.",
  "stickerrotate": "Creates or processes stickers.",
  "stickerblur": "Creates or processes stickers.",
  "stickersharpen": "Creates or processes stickers.",
  "stickerborder": "Creates or processes stickers.",
  "stickerround": "Creates or processes stickers.",
  "stickerframe": "Creates or processes stickers.",
  "stickercolor": "Creates or processes stickers.",
  "stickerbg": "Creates or processes stickers.",
  "stickerremovebg": "Creates or processes stickers.",
  "stickerupscale": "Creates or processes stickers.",
  "stickeranime": "Creates or processes stickers.",
  "toimage": "Provides the toimage command's related bot function.",
  "tovideo": "Provides the tovideo command's related bot function.",
  "togif": "Provides the togif command's related bot function.",
  "toaudio": "Provides the toaudio command's related bot function.",
  "tomp4": "Provides the tomp4 command's related bot function.",
  "tomp3x": "Provides the tomp3x command's related bot function.",
  "webptopng": "Provides the webptopng command's related bot function.",
  "pngtowebp": "Provides the pngtowebp command's related bot function.",
  "jpgtopng": "Provides the jpgtopng command's related bot function.",
  "pngtojpg": "Provides the pngtojpg command's related bot function.",
  "webptojpg": "Provides the webptojpg command's related bot function.",
  "mp4togif": "Provides the mp4togif command's related bot function.",
  "giftomp4": "Provides the giftomp4 command's related bot function.",
  "mp3togg": "Provides the mp3togg command's related bot function.",
  "mp4tomp3": "Provides the mp4tomp3 command's related bot function.",
  "compress": "Provides the compress command's related bot function.",
  "compressvideo": "Provides the compressvideo command's related bot function.",
  "compressimage": "Provides the compressimage command's related bot function.",
  "resize": "Provides the resize command's related bot function.",
  "resizeimage": "Provides the resizeimage command's related bot function.",
  "resizevideo": "Provides the resizevideo command's related bot function.",
  "crop": "Provides the crop command's related bot function.",
  "cropimage": "Provides the cropimage command's related bot function.",
  "cropvideo": "Provides the cropvideo command's related bot function.",
  "rotate": "Provides the rotate command's related bot function.",
  "flip": "Provides the flip command's related bot function.",
  "mirror": "Provides the mirror command's related bot function.",
  "blur": "Provides the blur command's related bot function.",
  "sharpen": "Provides the sharpen command's related bot function.",
  "enhance": "Enhances image quality.",
  "enhanceimage": "Enhances image quality.",
  "enhancevideo": "Enhances image quality.",
  "color": "Provides the color command's related bot function.",
  "grayscale": "Provides the grayscale command's related bot function.",
  "sepia": "Provides the sepia command's related bot function.",
  "invert": "Provides the invert command's related bot function.",
  "brightness": "Provides the brightness command's related bot function.",
  "contrast": "Provides the contrast command's related bot function.",
  "saturation": "Provides the saturation command's related bot function.",
  "hue": "Provides the hue command's related bot function.",
  "vintage": "Provides the vintage command's related bot function.",
  "cinematic": "Provides the cinematic command's related bot function.",
  "animefilter": "Provides an anime-related result or media.",
  "sketch": "Provides the sketch command's related bot function.",
  "oilpaint": "Provides the oilpaint command's related bot function.",
  "pixel": "Provides the pixel command's related bot function.",
  "glitchfx": "Provides the glitchfx command's related bot function.",
  "neonfx": "Provides the neonfx command's related bot function.",
  "newssearch": "Searches for information or content.",
  "newstoday": "Searches for information or content.",
  "headlines": "Provides the headlines command's related bot function.",
  "weathernews": "Provides the weathernews command's related bot function.",
  "technews": "Provides the technews command's related bot function.",
  "sportsnews": "Provides the sportsnews command's related bot function.",
  "moviesearch": "Processes or fetches video content.",
  "songsearch": "Provides the songsearch command's related bot function.",
  "artistsearch": "Provides the artistsearch command's related bot function.",
  "lyricssearch": "Provides the lyricssearch command's related bot function.",
  "booksearch": "Provides the booksearch command's related bot function.",
  "appsearch": "Provides the appsearch command's related bot function.",
  "gamesearch": "Runs a game, quiz, challenge, or interactive activity.",
  "imagesearch": "Processes, searches, or transforms images.",
  "imagedl": "Processes, searches, or transforms images.",
  "gifsearch": "Provides the gifsearch command's related bot function.",
  "gifdl": "Provides the gifdl command's related bot function.",
  "memesearch": "Provides the memesearch command's related bot function.",
  "memedl": "Provides the memedl command's related bot function.",
  "wallpaper": "Provides the wallpaper command's related bot function.",
  "wallpapersearch": "Provides the wallpapersearch command's related bot function.",
  "wallpaperdl": "Provides the wallpaperdl command's related bot function.",
  "image": "Processes, searches, or transforms images.",
  "image2": "Processes, searches, or transforms images.",
  "image3": "Processes, searches, or transforms images.",
  "image4": "Processes, searches, or transforms images.",
  "imagesearch2": "Processes, searches, or transforms images.",
  "reverseimage": "Formats, transforms, or analyzes text.",
  "imageinfo": "Processes, searches, or transforms images.",
  "imageurl": "Processes, searches, or transforms images.",
  "imagecrop": "Processes, searches, or transforms images.",
  "imagesize": "Processes, searches, or transforms images.",
  "imagecompress": "Processes, searches, or transforms images.",
  "imagequality": "Processes, searches, or transforms images.",
  "imageclear": "Processes, searches, or transforms images.",
  "imagefix": "Processes, searches, or transforms images.",
  "imageresize": "Processes, searches, or transforms images.",
  "imageconvert": "Processes, searches, or transforms images.",
  "imageformat": "Processes, searches, or transforms images.",
  "imageborder": "Processes, searches, or transforms images.",
  "imageframe": "Processes, searches, or transforms images.",
  "imagebackground": "Processes, searches, or transforms images.",
  "imageblur": "Processes, searches, or transforms images.",
  "imageunblur": "Processes, searches, or transforms images.",
  "imageenhance": "Processes, searches, or transforms images.",
  "imageupscale": "Processes, searches, or transforms images.",
  "imagecolor": "Processes, searches, or transforms images.",
  "imagecolorize": "Processes, searches, or transforms images.",
  "imageblackwhite": "Processes, searches, or transforms images.",
  "imagegray": "Processes, searches, or transforms images.",
  "imageinvert": "Processes, searches, or transforms images.",
  "imageflip": "Processes, searches, or transforms images.",
  "imagerotate": "Processes, searches, or transforms images.",
  "imagemirror": "Processes, searches, or transforms images.",
  "imagepixel": "Processes, searches, or transforms images.",
  "imagecartoon": "Processes, searches, or transforms images.",
  "imageanime": "Processes, searches, or transforms images.",
  "imagesketch": "Processes, searches, or transforms images.",
  "imageoil": "Processes, searches, or transforms images.",
  "imagewatercolor": "Processes, searches, or transforms images.",
  "imagecomic": "Processes, searches, or transforms images.",
  "image3d": "Processes, searches, or transforms images.",
  "imagehd": "Processes, searches, or transforms images.",
  "image4k": "Processes, searches, or transforms images.",
  "image8k": "Processes, searches, or transforms images.",
  "removeobject": "Provides the removeobject command's related bot function.",
  "objectremove": "Provides the objectremove command's related bot function.",
  "background": "Provides the background command's related bot function.",
  "backgroundblur": "Provides the backgroundblur command's related bot function.",
  "backgroundremove": "Provides the backgroundremove command's related bot function.",
  "backgroundchange": "Provides the backgroundchange command's related bot function.",
  "faceblur": "Provides the faceblur command's related bot function.",
  "facepixel": "Provides the facepixel command's related bot function.",
  "facecrop": "Provides the facecrop command's related bot function.",
  "faceswap": "Provides the faceswap command's related bot function.",
  "faceenhance": "Provides the faceenhance command's related bot function.",
  "portrait": "Processes, searches, or transforms images.",
  "portraitenhance": "Processes, searches, or transforms images.",
  "photoenhance": "Processes, searches, or transforms images.",
  "photofix": "Processes, searches, or transforms images.",
  "oldphoto": "Provides the oldphoto command's related bot function.",
  "restorephoto": "Provides the restorephoto command's related bot function.",
  "colorrestore": "Provides the colorrestore command's related bot function.",
  "deblur": "Provides the deblur command's related bot function.",
  "denoise": "Provides the denoise command's related bot function.",
  "noise": "Provides the noise command's related bot function.",
  "sharpen2": "Provides the sharpen2 command's related bot function.",
  "hdr": "Provides the hdr command's related bot function.",
  "hdrimage": "Provides the hdrimage command's related bot function.",
  "nightimage": "Provides the nightimage command's related bot function.",
  "lighten": "Provides the lighten command's related bot function.",
  "darken": "Provides the darken command's related bot function.",
  "exposure": "Provides the exposure command's related bot function.",
  "vignette": "Provides the vignette command's related bot function.",
  "focus": "Provides the focus command's related bot function.",
  "autofix": "Provides the autofix command's related bot function.",
  "statusdl": "Handles WhatsApp status-related content or actions.",
  "statussave": "Handles WhatsApp status-related content or actions.",
  "statusreact": "Handles WhatsApp status-related content or actions.",
  "statusdownload": "Handles WhatsApp status-related content or actions.",
  "statusmute": "Handles WhatsApp status-related content or actions.",
  "statusunmute": "Handles WhatsApp status-related content or actions.",
  "statusprivacy": "Handles WhatsApp status-related content or actions.",
  "statusarchive": "Handles WhatsApp status-related content or actions.",
  "statusclear": "Handles WhatsApp status-related content or actions.",
  "statushistory": "Handles WhatsApp status-related content or actions.",
  "statusinfo": "Handles WhatsApp status-related content or actions.",
  "statustext": "Handles WhatsApp status-related content or actions.",
  "statusimage": "Handles WhatsApp status-related content or actions.",
  "statusvideo": "Handles WhatsApp status-related content or actions.",
  "statusgif": "Handles WhatsApp status-related content or actions.",
  "statusaudio": "Handles WhatsApp status-related content or actions.",
  "statussticker": "Handles WhatsApp status-related content or actions.",
  "statusquote": "Handles WhatsApp status-related content or actions.",
  "statuspoll": "Handles WhatsApp status-related content or actions.",
  "statusquestion": "Handles WhatsApp status-related content or actions.",
  "statusmusic": "Handles WhatsApp status-related content or actions.",
  "statussong": "Handles WhatsApp status-related content or actions.",
  "statuscaption": "Handles WhatsApp status-related content or actions.",
  "statusfont": "Handles WhatsApp status-related content or actions.",
  "statuscolor": "Handles WhatsApp status-related content or actions.",
  "statusbg": "Handles WhatsApp status-related content or actions.",
  "statusgradient": "Handles WhatsApp status-related content or actions.",
  "statusborder": "Handles WhatsApp status-related content or actions.",
  "statusframe": "Handles WhatsApp status-related content or actions.",
  "statuscard": "Handles WhatsApp status-related content or actions.",
  "statusposter": "Handles WhatsApp status-related content or actions.",
  "statusstory": "Handles WhatsApp status-related content or actions.",
  "story": "Handles story-style content or actions.",
  "storydl": "Handles story-style content or actions.",
  "storysave": "Handles story-style content or actions.",
  "storyview": "Handles story-style content or actions.",
  "storyreply": "Handles story-style content or actions.",
  "storyreact": "Handles story-style content or actions.",
  "storymention": "Handles story-style content or actions.",
  "storyshare": "Handles story-style content or actions.",
  "storymusic": "Handles story-style content or actions.",
  "storytext": "Handles story-style content or actions.",
  "storyimage": "Handles story-style content or actions.",
  "storyvideo": "Handles story-style content or actions.",
  "storygif": "Handles story-style content or actions.",
  "security": "Provides a security, moderation, or verification function.",
  "securityinfo": "Provides a security, moderation, or verification function.",
  "antispam2": "Provides a security, moderation, or verification function.",
  "antiflood2": "Provides a security, moderation, or verification function.",
  "antiraid2": "Provides a security, moderation, or verification function.",
  "anticrash": "Provides a security, moderation, or verification function.",
  "antivirus": "Provides a security, moderation, or verification function.",
  "viruscheck": "Provides a security, moderation, or verification function.",
  "malwarecheck": "Provides a security, moderation, or verification function.",
  "linkcheck": "Provides the linkcheck command's related bot function.",
  "urlscan": "Checks or retrieves network/website information.",
  "phishingcheck": "Provides a security, moderation, or verification function.",
  "scamcheck": "Provides a security, moderation, or verification function.",
  "safecheck": "Provides the safecheck command's related bot function.",
  "textscan": "Formats, transforms, or analyzes text.",
  "messagescan": "Provides the messagescan command's related bot function.",
  "filecheck": "Provides the filecheck command's related bot function.",
  "documentcheck": "Provides the documentcheck command's related bot function.",
  "imagecheck": "Processes, searches, or transforms images.",
  "videocheck": "Processes or fetches video content.",
  "audioscan": "Processes or converts audio/voice content.",
  "spamcheck": "Provides the spamcheck command's related bot function.",
  "numbercheck": "Provides the numbercheck command's related bot function.",
  "usercheck": "Provides the usercheck command's related bot function.",
  "accountcheck": "Provides the accountcheck command's related bot function.",
  "sessioncheck": "Provides the sessioncheck command's related bot function.",
  "devicecheck": "Provides the devicecheck command's related bot function.",
  "devices": "Provides the devices command's related bot function.",
  "sessions": "Provides the sessions command's related bot function.",
  "sessionlist": "Provides the sessionlist command's related bot function.",
  "logincheck": "Provides the logincheck command's related bot function.",
  "auth": "Provides the auth command's related bot function.",
  "verify": "Provides a security, moderation, or verification function.",
  "verification": "Provides the verification command's related bot function.",
  "verifyuser": "Provides a security, moderation, or verification function.",
  "otp": "Provides a security, moderation, or verification function.",
  "generateotp": "Provides the generateotp command's related bot function.",
  "securitycode": "Provides a security, moderation, or verification function.",
  "lockbot": "Provides the lockbot command's related bot function.",
  "unlockbot": "Provides the unlockbot command's related bot function.",
  "lockowner": "Provides the lockowner command's related bot function.",
  "unlockowner": "Provides the unlockowner command's related bot function.",
  "panic": "Provides the panic command's related bot function.",
  "emergency": "Provides the emergency command's related bot function.",
  "emergencyoff": "Provides the emergencyoff command's related bot function.",
  "maintenance": "Provides the maintenance command's related bot function.",
  "maintenanceoff": "Provides the maintenanceoff command's related bot function.",
  "backupsecurity": "Provides the backupsecurity command's related bot function.",
  "securitylog": "Provides a security, moderation, or verification function.",
  "audit": "Provides a security, moderation, or verification function.",
  "auditlog": "Provides a security, moderation, or verification function.",
  "activity": "Provides the activity command's related bot function.",
  "activitylog": "Provides the activitylog command's related bot function.",
  "loginlog": "Provides the loginlog command's related bot function.",
  "commandlog": "Provides the commandlog command's related bot function.",
  "errorlog": "Provides the errorlog command's related bot function.",
  "clearlog": "Provides the clearlog command's related bot function.",
  "clearsession": "Provides the clearsession command's related bot function.",
  "resetsecurity": "Changes or manages a bot setting.",
  "blocklist2": "Blocks or restricts a user.",
  "allowlist": "Provides the allowlist command's related bot function.",
  "whitelist": "Provides a security, moderation, or verification function.",
  "blacklist": "Provides a security, moderation, or verification function.",
  "trusted": "Provides the trusted command's related bot function.",
  "untrusted": "Provides the untrusted command's related bot function.",
  "setregion": "Changes or manages a bot setting.",
  "region": "Changes or manages a bot setting.",
  "setprefix": "Changes or manages a bot setting.",
  "punjabi": "Translates or processes language text.",
  "sindhi": "Translates or processes language text.",
  "saraiki": "Translates or processes language text.",
  "translateauto": "Translates or processes language text.",
  "detectlang": "Provides the detectlang command's related bot function.",
  "langdetect": "Provides the langdetect command's related bot function.",
  "dictionary": "Provides the dictionary command's related bot function.",
  "meaning": "Provides the meaning command's related bot function.",
  "meaning2": "Provides the meaning2 command's related bot function.",
  "synonym": "Provides the synonym command's related bot function.",
  "synonyms": "Provides the synonyms command's related bot function.",
  "antonym": "Provides the antonym command's related bot function.",
  "antonyms": "Provides the antonyms command's related bot function.",
  "definition": "Provides the definition command's related bot function.",
  "define2": "Provides the define2 command's related bot function.",
  "pronounce": "Provides the pronounce command's related bot function.",
  "pronunciation": "Provides the pronunciation command's related bot function.",
  "spell": "Provides the spell command's related bot function.",
  "spellcheck": "Provides the spellcheck command's related bot function.",
  "sentence": "Provides the sentence command's related bot function.",
  "sentencefix": "Provides the sentencefix command's related bot function.",
  "paraphrase": "Provides the paraphrase command's related bot function.",
  "rewrite": "Provides the rewrite command's related bot function.",
  "rephrase": "Provides the rephrase command's related bot function.",
  "summarize": "Performs a mathematical calculation.",
  "shorten": "Provides the shorten command's related bot function.",
  "expand": "Provides the expand command's related bot function.",
  "formal": "Provides the formal command's related bot function.",
  "informal": "Provides the informal command's related bot function.",
  "professional": "Provides the professional command's related bot function.",
  "casual": "Provides the casual command's related bot function.",
  "uppercase2": "Formats, transforms, or analyzes text.",
  "lowercase2": "Formats, transforms, or analyzes text.",
  "profile2": "Manages or generates profile/social information.",
  "userinfo": "Provides the userinfo command's related bot function.",
  "userinfo2": "Provides the userinfo2 command's related bot function.",
  "avatar": "Manages or generates profile/social information.",
  "avatar2": "Manages or generates profile/social information.",
  "getavatar": "Provides the getavatar command's related bot function.",
  "getdp": "Provides the getdp command's related bot function.",
  "dp": "Manages or generates profile/social information.",
  "setdp": "Changes or manages a bot setting.",
  "cover": "Manages or generates profile/social information.",
  "getcover": "Provides the getcover command's related bot function.",
  "setcover": "Changes or manages a bot setting.",
  "bio2": "Manages or generates profile/social information.",
  "setbio2": "Changes or manages a bot setting.",
  "aboutme": "Provides the aboutme command's related bot function.",
  "myinfo": "Provides the myinfo command's related bot function.",
  "id2": "Provides the id2 command's related bot function.",
  "jid": "Provides the jid command's related bot function.",
  "jid2": "Provides the jid2 command's related bot function.",
  "mention": "Provides the mention command's related bot function.",
  "mention2": "Provides the mention2 command's related bot function.",
  "taguser": "Provides the taguser command's related bot function.",
  "tagusers": "Provides the tagusers command's related bot function.",
  "savecontact": "Provides the savecontact command's related bot function.",
  "vcard": "Manages or generates profile/social information.",
  "businesscard": "Provides the businesscard command's related bot function.",
  "qrcontact": "Generates or reads a QR/barcode-related result.",
  "sharecontact": "Provides the sharecontact command's related bot function.",
  "statusmaker": "Handles WhatsApp status-related content or actions.",
  "statusgenerator": "Handles WhatsApp status-related content or actions.",
  "storymaker": "Handles story-style content or actions.",
  "storygenerator": "Handles story-style content or actions.",
  "profilecard": "Manages or generates profile/social information.",
  "profilepic": "Manages or generates profile/social information.",
  "profilemaker": "Manages or generates profile/social information.",
  "namecard": "Provides the namecard command's related bot function.",
  "namecard2": "Provides the namecard2 command's related bot function.",
  "birthday": "Manages or generates profile/social information.",
  "birthdaycard": "Manages or generates profile/social information.",
  "birthdaywish": "Manages or generates profile/social information.",
  "wish": "Manages or generates profile/social information.",
  "wishes": "Manages or generates profile/social information.",
  "congratulate": "Provides the congratulate command's related bot function.",
  "congrats": "Provides the congrats command's related bot function.",
  "thankyou": "Provides the thankyou command's related bot function.",
  "sorrycard": "Provides the sorrycard command's related bot function.",
  "goodmorning": "Provides the goodmorning command's related bot function.",
  "goodnight": "Provides the goodnight command's related bot function.",
  "goodafternoon": "Provides the goodafternoon command's related bot function.",
  "goodevening": "Provides the goodevening command's related bot function.",
  "welcome2": "Provides the welcome2 command's related bot function.",
  "farewell": "Provides the farewell command's related bot function.",
  "goodluck": "Provides the goodluck command's related bot function.",
  "allthebest": "Provides the allthebest command's related bot function.",
  "getwell": "Provides the getwell command's related bot function.",
  "festival": "Provides the festival command's related bot function.",
  "festivalwish": "Provides the festivalwish command's related bot function.",
  "eidwish": "Provides the eidwish command's related bot function.",
  "ramadan": "Provides the ramadan command's related bot function.",
  "ramadanwish": "Provides the ramadanwish command's related bot function.",
  "jumma": "Provides the jumma command's related bot function.",
  "jummawish": "Provides the jummawish command's related bot function.",
  "newyear": "Provides the newyear command's related bot function.",
  "newyearwish": "Provides the newyearwish command's related bot function.",
  "birthdaywish2": "Manages or generates profile/social information.",
  "audio": "Processes or converts audio/voice content.",
  "audio2": "Processes or converts audio/voice content.",
  "audio3": "Processes or converts audio/voice content.",
  "audioinfo": "Processes or converts audio/voice content.",
  "voicetotext": "Processes or converts audio/voice content.",
  "record": "Provides the record command's related bot function.",
  "recordaudio": "Provides the recordaudio command's related bot function.",
  "recordvoice": "Provides the recordvoice command's related bot function.",
  "videoinfo": "Processes or fetches video content.",
  "videocut": "Processes or fetches video content.",
  "videojoin": "Processes or fetches video content.",
  "videospeed": "Processes or fetches video content.",
  "videoflip": "Processes or fetches video content.",
  "videorotate": "Processes or fetches video content.",
  "videomirror": "Processes or fetches video content.",
  "videofilter": "Processes or fetches video content.",
  "videoframe": "Processes or fetches video content.",
  "videowatermark": "Processes or fetches video content.",
  "videotext": "Processes or fetches video content.",
  "videocaption": "Processes or fetches video content.",
  "videoaudio": "Processes or fetches video content.",
  "videomute": "Processes or fetches video content.",
  "videoextract": "Processes or fetches video content.",
  "thumbnail": "Provides the thumbnail command's related bot function.",
  "thumbnail2": "Provides the thumbnail2 command's related bot function.",
  "thumbnails": "Provides the thumbnails command's related bot function.",
  "gif": "Provides the gif command's related bot function.",
  "gif2": "Provides the gif2 command's related bot function.",
  "gifmaker": "Provides the gifmaker command's related bot function.",
  "gifconvert": "Provides the gifconvert command's related bot function.",
  "gifsearch2": "Provides the gifsearch2 command's related bot function.",
  "gifdl2": "Provides the gifdl2 command's related bot function.",
};
module.exports.commands = Object.keys(XDESC).map(name => ({
  name,
  desc: XDESC[name],
  category: "ADMIN",
  handler: async (m, sock) => {
    const r = await handler(m, sock);
    if (r === null || r === undefined) return m.reply('🛡️ ' + XDESC[name] + '\n→ Try: .' + name + ' <input> — ya .help dekho');
    return r;
  },
}));
